"""Platform capability registry for Lingchu Bot."""

from .registry import (
    UNKNOWN_PLATFORM_ID,
    PlatformAdapterConflictError,
    PlatformAdapterNotLoadedError,
    PlatformAdapterUnknownError,
    PlatformCapability,
    PlatformProfile,
    get_platform_profile,
    get_supported_adapter_names,
    get_supported_adapters,
    is_adapter_enabled,
    is_known_adapter,
    iter_platform_profiles,
    parse_configured_adapters,
    resolve_adapter_id,
    resolve_enabled_adapters,
    resolve_registered_adapters,
    validate_enabled_adapters_loaded,
    validate_platform_adapter_selection,
)

__all__ = [
    "UNKNOWN_PLATFORM_ID",
    "PlatformAdapterConflictError",
    "PlatformAdapterNotLoadedError",
    "PlatformAdapterUnknownError",
    "PlatformCapability",
    "PlatformProfile",
    "get_platform_profile",
    "get_supported_adapter_names",
    "get_supported_adapters",
    "is_adapter_enabled",
    "is_known_adapter",
    "iter_platform_profiles",
    "parse_configured_adapters",
    "resolve_adapter_id",
    "resolve_enabled_adapters",
    "resolve_registered_adapters",
    "validate_enabled_adapters_loaded",
    "validate_platform_adapter_selection",
]
