# syntax=docker/dockerfile:1.7

# ── Builder stage ────────────────────────────────────────────────────────────
# Uses slim image + build tools for wheel compilation. The builder is discarded
# in the final image, so build tools do not affect the runtime image size.
FROM python:3.13-slim@sha256:7ba5f5888fbe0014ab9edb2278922995c2201fc3752c46b0be24763eb46fa9f3 AS requirements_stage

# Install build tools for any C-extension dependencies that lack pre-built
# wheels for this platform. The builder stage is discarded, so these do not
# bloat the runtime image.
RUN apt-get update && apt-get install -y --no-install-recommends \
      gcc python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /wheel

RUN python -m pip install --user uv

COPY ./pyproject.toml ./uv.lock /wheel/

# Export only third-party runtime dependencies (no dev group). --no-emit-project
# excludes the local ``-e .`` entry so the builder does not need README/license
# files; the source is copied into the runtime stage directly.
RUN python -m uv export --frozen --no-dev --all-extras --no-emit-project --no-hashes \
      --output-file requirements.txt

# Build wheels for offline installation in the runtime stage.
RUN python -m pip wheel --wheel-dir=/wheels --no-cache-dir --requirement ./requirements.txt

# Generate bot.py via nb-cli (used by ``nb run`` in the smoke-test path).
RUN python -m uv tool run --no-cache --from nb-cli nb generate -f /tmp/bot.py


# ── Project build stage ─────────────────────────────────────────────────────
# Build the project wheel with all modules (nonebot_plugin_lingchu_bot,
# _lingchu_bot_cli, _lingchu_bot_contracts) for installation in the runtime image.
FROM requirements_stage AS project_build
WORKDIR /build
COPY . /build/
RUN python -m uv build --wheel --no-sources --out-dir /dist


# ── Runtime stage ────────────────────────────────────────────────────────────
FROM python:3.13-slim@sha256:7ba5f5888fbe0014ab9edb2278922995c2201fc3752c46b0be24763eb46fa9f3

WORKDIR /app

# ── OCI labels ──
# Build args are passed by CI (👷-ci-builds.yml, 🚀-release.yml).
# VCS_REF is mapped to org.opencontainers.image.revision because release.yml
# passes VCS_REF=${{ github.sha }} as a build-arg.
ARG VERSION=unknown
ARG VCS_REF=unknown
ARG CREATED=unknown
ARG REVISION=unknown
LABEL org.opencontainers.image.title="Lingchu Bot" \
  org.opencontainers.image.description="NoneBot2-powered application-side group management bot" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${VCS_REF}" \
  org.opencontainers.image.source="https://github.com/xinvxueyuan/lingchu-bot" \
  org.opencontainers.image.url="https://lingchu.zone.id/" \
  org.opencontainers.image.licenses="LGPL-3.0-or-later" \
  org.opencontainers.image.documentation="https://lingchu.zone.id/" \
  org.opencontainers.image.created="${CREATED}"

ENV TZ=Asia/Shanghai
ENV PYTHONPATH=/app

# ── Non-root user ──
RUN groupadd --system app \
  && useradd --system --gid app --home-dir /app --shell /usr/sbin/nologin app \
  && chown -R app:app /app

# ── Install dependencies from pre-built wheels ──
COPY --from=requirements_stage /wheels /wheels
COPY --from=requirements_stage /wheel/requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --no-index --find-links=/wheels -r /tmp/requirements.txt \
  && rm -rf /wheels /tmp/requirements.txt

# ── Install project wheel ──
# Install the wheel containing all three modules (nonebot_plugin_lingchu_bot,
# _lingchu_bot_cli, _lingchu_bot_contracts) built in the project_build stage.
COPY --from=project_build /dist/*.whl /tmp/
RUN pip install --no-cache-dir /tmp/*.whl && rm /tmp/*.whl

# ── Copy bot.py (generated by nb-cli) ──
COPY --from=requirements_stage --chown=app:app /tmp/bot.py /app/bot.py

# ── Smoke-test support ──
# Expose a build-time flag, copy the entrypoint script and install nb-cli
# only when smoke tests are requested so the production image stays unchanged.
ARG SMOKE_TEST=false
ENV SMOKE_TEST=${SMOKE_TEST}
COPY --chown=app:app ./docker/smoke-test.py /app/docker/smoke-test.py
RUN if [ "${SMOKE_TEST}" = "true" ]; then pip install --no-cache-dir nb-cli; fi

USER app

# ── Healthcheck ──
# Verifies the FastAPI server is accepting TCP connections on PORT (default 8080).
# start-period gives NoneBot time to run migrations and load plugins before
# the healthcheck starts counting failures.
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD python -c "import socket, os; p=int(os.getenv('PORT','8080')); s=socket.socket(); s.connect(('localhost', p)); s.close()"

# ── Entrypoint ──
# A conditional CMD is required because the CI smoke-test job (👷-ci-builds.yml)
# invokes the image without a command override and selects the branch via
# SMOKE_TEST=true. The production branch uses ``exec`` so NoneBot receives
# process signals directly (equivalent to exec-form ENTRYPOINT).
CMD if [ "${SMOKE_TEST}" = "true" ]; then exec python /app/docker/smoke-test.py; else exec python -m nonebot; fi
