packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@go-task/cli': true
  '@ladybugdb/core': true
  '@scarf/scarf': true
  esbuild: true
  gitnexus: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  tree-sitter: true
  tree-sitter-c: true
  tree-sitter-c-sharp: true
  tree-sitter-cpp: true
  tree-sitter-go: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-kotlin: true
  tree-sitter-php: true
  tree-sitter-python: true
  tree-sitter-ruby: true
  tree-sitter-rust: true
  tree-sitter-typescript: true
  unrs-resolver: true
