"""initial schema

迁移 ID: 30f5a01259cd
父迁移:
创建时间: 2026-06-19 01:42:54.556496

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "30f5a01259cd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_lingchu_bot",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lingchu_message_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("bot_id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=True),
        sa.Column("message_id", sa.String(length=128), nullable=True),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("message_type", sa.String(length=64), nullable=True),
        sa.Column("text_summary", sa.Text(), nullable=True),
        sa.Column("raw_message", sa.Text(), nullable=True),
        sa.Column("raw_event", sa.Text(), nullable=True),
        sa.Column("process_status", sa.String(length=32), nullable=False),
        sa.Column("exception_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingchu_message_records")),
        sa.UniqueConstraint(
            "platform",
            "adapter",
            "bot_id",
            "conversation_id",
            "message_id",
            name="uq_lingchu_message_record_identity",
        ),
        info={"bind_key": "nonebot_plugin_lingchu_bot"},
    )
    op.create_index(
        op.f("ix_lingchu_message_records_platform"),
        "lingchu_message_records",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_adapter"),
        "lingchu_message_records",
        ["adapter"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_bot_id"),
        "lingchu_message_records",
        ["bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_conversation_id"),
        "lingchu_message_records",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_user_id"),
        "lingchu_message_records",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_message_id"),
        "lingchu_message_records",
        ["message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_event_type"),
        "lingchu_message_records",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_message_type"),
        "lingchu_message_records",
        ["message_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_process_status"),
        "lingchu_message_records",
        ["process_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_created_at"),
        "lingchu_message_records",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_message_records_updated_at"),
        "lingchu_message_records",
        ["updated_at"],
        unique=False,
    )

    op.create_table(
        "lingchu_audit_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform", sa.String(length=64), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("bot_id", sa.String(length=128), nullable=False),
        sa.Column("audit_type", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("data_summary", sa.Text(), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("exception_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingchu_audit_records")),
        info={"bind_key": "nonebot_plugin_lingchu_bot"},
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_platform"),
        "lingchu_audit_records",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_adapter"),
        "lingchu_audit_records",
        ["adapter"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_bot_id"),
        "lingchu_audit_records",
        ["bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_audit_type"),
        "lingchu_audit_records",
        ["audit_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_event_type"),
        "lingchu_audit_records",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_audit_records_created_at"),
        "lingchu_audit_records",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "lingchu_blocklist_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.String(length=64), nullable=False),
        sa.Column("adapter_id", sa.String(length=64), nullable=False),
        sa.Column("bot_id", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_key", sa.String(length=128), nullable=False),
        sa.Column("group_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("operator_id", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lingchu_blocklist_entries")),
        sa.UniqueConstraint(
            "platform_id",
            "adapter_id",
            "bot_id",
            "scope",
            "scope_key",
            "user_id",
            name="uq_lingchu_blocklist_entry_identity",
        ),
        info={"bind_key": "nonebot_plugin_lingchu_bot"},
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_platform_id"),
        "lingchu_blocklist_entries",
        ["platform_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_adapter_id"),
        "lingchu_blocklist_entries",
        ["adapter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_bot_id"),
        "lingchu_blocklist_entries",
        ["bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_scope"),
        "lingchu_blocklist_entries",
        ["scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_scope_key"),
        "lingchu_blocklist_entries",
        ["scope_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_group_id"),
        "lingchu_blocklist_entries",
        ["group_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_user_id"),
        "lingchu_blocklist_entries",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_operator_id"),
        "lingchu_blocklist_entries",
        ["operator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_expires_at"),
        "lingchu_blocklist_entries",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_created_at"),
        "lingchu_blocklist_entries",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lingchu_blocklist_entries_updated_at"),
        "lingchu_blocklist_entries",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_updated_at"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_created_at"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_expires_at"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_operator_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_user_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_group_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_scope_key"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_scope"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_bot_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_adapter_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_index(
        op.f("ix_lingchu_blocklist_entries_platform_id"),
        table_name="lingchu_blocklist_entries",
    )
    op.drop_table("lingchu_blocklist_entries")

    op.drop_index(
        op.f("ix_lingchu_audit_records_created_at"),
        table_name="lingchu_audit_records",
    )
    op.drop_index(
        op.f("ix_lingchu_audit_records_event_type"),
        table_name="lingchu_audit_records",
    )
    op.drop_index(
        op.f("ix_lingchu_audit_records_audit_type"),
        table_name="lingchu_audit_records",
    )
    op.drop_index(
        op.f("ix_lingchu_audit_records_bot_id"),
        table_name="lingchu_audit_records",
    )
    op.drop_index(
        op.f("ix_lingchu_audit_records_adapter"),
        table_name="lingchu_audit_records",
    )
    op.drop_index(
        op.f("ix_lingchu_audit_records_platform"),
        table_name="lingchu_audit_records",
    )
    op.drop_table("lingchu_audit_records")

    op.drop_index(
        op.f("ix_lingchu_message_records_updated_at"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_created_at"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_process_status"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_message_type"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_event_type"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_message_id"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_user_id"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_conversation_id"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_bot_id"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_adapter"),
        table_name="lingchu_message_records",
    )
    op.drop_index(
        op.f("ix_lingchu_message_records_platform"),
        table_name="lingchu_message_records",
    )
    op.drop_table("lingchu_message_records")
    # ### end Alembic commands ###
