"""Project-owned contracts and services for the inbound MCP control plane."""

from .contracts import (
    BotAddress,
    CapabilityScope,
    ConnectedBotSummary,
    ContractError,
    ConversationAddress,
    ErrorCode,
    ImageSegment,
    ListRecentMessagesRequest,
    ListRecentMessagesResult,
    MessageAction,
    MessageCursor,
    MessageEnvelope,
    MessageProvider,
    MessageQuery,
    OperationStatus,
    ResourceGrant,
    SendMessageRequest,
    SendMessageResult,
    ServicePrincipal,
    TextSegment,
)
from .send_orchestrator import IdempotencyLedger, SendMessageOrchestrator

__all__ = [
    "BotAddress",
    "CapabilityScope",
    "ConnectedBotSummary",
    "ContractError",
    "ConversationAddress",
    "ErrorCode",
    "IdempotencyLedger",
    "ImageSegment",
    "ListRecentMessagesRequest",
    "ListRecentMessagesResult",
    "MessageAction",
    "MessageCursor",
    "MessageEnvelope",
    "MessageProvider",
    "MessageQuery",
    "OperationStatus",
    "ResourceGrant",
    "SendMessageOrchestrator",
    "SendMessageRequest",
    "SendMessageResult",
    "ServicePrincipal",
    "TextSegment",
]
