"""lc db — drive Alembic migrations through nonebot-plugin-orm."""

from __future__ import annotations

import typer

from lingc_cli.console import get_console
from lingc_cli.exceptions import LingcCliError
from lingc_cli.handlers.db import run_db
from lingc_cli.i18n import _


def _run(args: list[str]) -> None:
    """Run an orm subcommand and translate the result to a Typer exit code."""
    try:
        exit_code = run_db(args)
    except LingcCliError as exc:
        get_console(stderr=True).print(
            _("error: {message}").format(message=exc), style="bold red", markup=False
        )
        raise typer.Exit(1) from exc
    if exit_code != 0:
        raise typer.Exit(exit_code)


def register(app: typer.Typer) -> None:
    """Register the db sub-application onto the root application."""
    db_app = typer.Typer(help=_("Manage the database schema with migrations."))

    @db_app.command("upgrade", help=_("Upgrade the database to a newer revision."))
    def upgrade() -> None:
        """Apply all pending migrations."""
        _run(["upgrade"])

    @db_app.command("check", help=_("Check that the schema matches the models."))
    def check() -> None:
        """Verify the database is in sync with the model definitions."""
        _run(["check"])

    @db_app.command("revision", help=_("Create a new migration script."))
    def revision(
        message: str | None = typer.Option(
            None, "--message", "-m", help=_("Revision message.")
        ),
        branch_label: str | None = typer.Option(
            None, "--branch-label", help=_("Migration branch label.")
        ),
    ) -> None:
        """Generate a new autogenerated migration script."""
        args = ["revision"]
        if message:
            args += ["--message", message]
        if branch_label:
            args += ["--branch-label", branch_label]
        _run(args)

    @db_app.command("sync", help=_("Synchronize the schema (development only)."))
    def sync() -> None:
        """Recreate the schema directly from the models."""
        _run(["sync"])

    app.add_typer(db_app, name="db")


__all__ = ["register"]
