"""Nested subplugin discovery and parent-child contracts."""

from .contracts import (
    LLMOptions,
    LocalizedText,
    MenuAvailability,
    MenuFeature,
    PlatformCapability,
    SubpluginLLMError,
    SubpluginTrigger,
    collect_subplugin_menu_features,
    complete_subplugin_chat,
    complete_subplugin_chat_default,
    ensure_subplugin_config_file,
    get_configured_locale,
    get_subplugin_trigger,
    image_message,
    load_subplugin_config,
    register_subplugin_handler,
    register_subplugin_menu_feature,
    reset_subplugin_menu_features,
    resolve_default_llm_options,
)
from .loader import discover_subplugin_dirs, load_subplugins

__all__ = [
    "LLMOptions",
    "LocalizedText",
    "MenuAvailability",
    "MenuFeature",
    "PlatformCapability",
    "SubpluginLLMError",
    "SubpluginTrigger",
    "collect_subplugin_menu_features",
    "complete_subplugin_chat",
    "complete_subplugin_chat_default",
    "discover_subplugin_dirs",
    "ensure_subplugin_config_file",
    "get_configured_locale",
    "get_subplugin_trigger",
    "image_message",
    "load_subplugin_config",
    "load_subplugins",
    "register_subplugin_handler",
    "register_subplugin_menu_feature",
    "reset_subplugin_menu_features",
    "resolve_default_llm_options",
]
