# 从当前目录下的 menu 模块导入所有内容
from .menu import *
# 从当前目录下的 speech 模块导入所有内容
from .speech import *
# 从当前目录下的 member 模块导入所有内容
from .member import *
# 从当前目录下的 bulletin 模块导入所有内容
from .bulletin import *
# 从当前目录下的 list 模块导入所有内容
from .list import *
