"""Pure file operations for Lingchu runtime settings and their JSON Schema."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from _lingchu_bot_contracts import (
    MutableRuntimeSettings,
)
from pydantic import ValidationError
import rtoml

if TYPE_CHECKING:
    from pathlib import Path

CONFIG_FILENAME = "runtime-overrides.toml"
CONFIG_SCHEMA_FILENAME = "runtime-overrides.schema.json"
LLM_CONFIG_FILENAME = "llm.toml"
_SCHEMA_DIRECTIVE = "#:schema ./runtime-overrides.schema.json\n"
_LLM_TEMPLATE = 'default_profile = "default"\n[profiles]\n'


class ConfigFileError(RuntimeError):
    """Report an expected configuration file failure to CLI callers."""


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(f"{path.suffix}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def initialize_config(path: Path, *, force: bool = False) -> bool:
    """Create validated runtime defaults and return whether a file was written."""
    if path.exists() and not force:
        return False
    defaults = {
        key: value
        for key, value in MutableRuntimeSettings().model_dump(mode="json").items()
        if value is not None
    }
    _atomic_write(path, _SCHEMA_DIRECTIVE + rtoml.dumps(defaults))
    return True


def initialize_llm_config(path: Path) -> bool:
    """Create the default LLM profile template without overwriting any file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with path.open("x", encoding="utf-8") as file:
            file.write(_LLM_TEMPLATE)
    except FileExistsError:
        return False
    return True


def _load_raw_config(
    path: Path,
    *,
    allowed_fields: frozenset[str] = frozenset(MutableRuntimeSettings.model_fields),
) -> dict[str, object]:
    if not path.is_file():
        raise ConfigFileError(f"missing configuration file: {path}")
    try:
        raw = rtoml.load(path)
    except (OSError, rtoml.TomlParsingError) as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc
    unknown = sorted(set(raw) - allowed_fields)
    if unknown:
        raise ConfigFileError(f"unknown configuration fields: {', '.join(unknown)}")
    return raw


def validate_config(path: Path) -> MutableRuntimeSettings:
    """Validate one on-disk TOML file without environment overrides or writes."""
    raw = _load_raw_config(path)
    try:
        return MutableRuntimeSettings.model_validate(raw)
    except ValidationError as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc


def install_config_schema(config_dir: Path) -> Path:
    """Install the JSON Schema generated by the shared runtime settings model."""
    target = config_dir / CONFIG_SCHEMA_FILENAME
    content = json.dumps(
        MutableRuntimeSettings.model_json_schema(mode="serialization"),
        ensure_ascii=False,
        indent=2,
    )
    _atomic_write(target, f"{content}\n")
    return target
