"""Pure file operations for Lingchu runtime settings and their JSON Schema."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from typing import TYPE_CHECKING

from _lingchu_bot_contracts import (
    DEPLOYMENT_RUNTIME_FIELDS,
    MUTABLE_RUNTIME_FIELDS,
    MutableRuntimeSettings,
    RuntimeSettings,
)
from pydantic import ValidationError
import rtoml

if TYPE_CHECKING:
    from pathlib import Path

CONFIG_FILENAME = "runtime-overrides.toml"
CONFIG_SCHEMA_FILENAME = "runtime-overrides.schema.json"
_SCHEMA_DIRECTIVE = "#:schema ./runtime-overrides.schema.json\n"
_ENV_ASSIGNMENT = re.compile(
    r"^(?P<prefix>\s*(?:export\s+)?)(?P<key>[A-Za-z_][A-Za-z0-9_]*)(?P<separator>\s*=).*$"
)


class ConfigFileError(RuntimeError):
    """Report an expected configuration file failure to CLI callers."""


@dataclass(frozen=True, slots=True)
class ConfigMigrationResult:
    """Describe a migration without exposing configuration values."""

    deployment_keys: tuple[str, ...]
    residual_fields: tuple[str, ...]
    dry_run: bool


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(f"{path.suffix}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def initialize_config(path: Path, *, force: bool = False) -> bool:
    """Create validated runtime defaults and return whether a file was written."""
    if path.exists() and not force:
        return False
    defaults = {
        key: value
        for key, value in MutableRuntimeSettings().model_dump(mode="json").items()
        if value is not None
    }
    _atomic_write(path, _SCHEMA_DIRECTIVE + rtoml.dumps(defaults))
    return True


def _load_raw_config(
    path: Path,
    *,
    allowed_fields: frozenset[str] = frozenset(MutableRuntimeSettings.model_fields),
) -> dict[str, object]:
    if not path.is_file():
        raise ConfigFileError(f"missing configuration file: {path}")
    try:
        raw = rtoml.load(path)
    except (OSError, rtoml.TomlParsingError) as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc
    unknown = sorted(set(raw) - allowed_fields)
    if unknown:
        raise ConfigFileError(f"unknown configuration fields: {', '.join(unknown)}")
    return raw


def validate_config(path: Path) -> MutableRuntimeSettings:
    """Validate one on-disk TOML file without environment overrides or writes."""
    raw = _load_raw_config(path)
    try:
        return MutableRuntimeSettings.model_validate(raw)
    except ValidationError as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc


def install_config_schema(config_dir: Path) -> Path:
    """Install the JSON Schema generated by the shared runtime settings model."""
    target = config_dir / CONFIG_SCHEMA_FILENAME
    content = json.dumps(
        MutableRuntimeSettings.model_json_schema(mode="serialization"),
        ensure_ascii=False,
        indent=2,
    )
    _atomic_write(target, f"{content}\n")
    return target


def _environment_key(field_name: str) -> str:
    if field_name.startswith("lingchu_"):
        return field_name.upper()
    return f"LINGCHU_{field_name.upper()}"


def _environment_value(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _merge_environment(original: str, updates: dict[str, str], *, force: bool) -> str:
    lines = original.splitlines(keepends=True)
    indexes: dict[str, int] = {}
    current: dict[str, str] = {}
    for index, line in enumerate(lines):
        match = _ENV_ASSIGNMENT.match(line.rstrip("\r\n"))
        if match is None:
            continue
        key = match.group("key")
        indexes[key] = index
        current[key] = line.rstrip("\r\n").split("=", 1)[1].strip()

    conflicts = sorted(
        key
        for key, value in updates.items()
        if key in current and current[key] != value
    )
    if conflicts and not force:
        raise ConfigFileError("environment key conflict: " + ", ".join(conflicts))

    newline = "\r\n" if "\r\n" in original else "\n"
    if lines and not lines[-1].endswith(("\n", "\r")):
        lines[-1] += newline
    for key, value in updates.items():
        replacement = f"{key}={value}{newline}"
        if key in indexes:
            if force or current[key] == value:
                lines[indexes[key]] = replacement
        else:
            lines.append(replacement)
    return "".join(lines)


def _write_migration_targets(
    env_file: Path,
    env_content: str,
    residual_file: Path,
    residual_content: str,
) -> None:
    env_existed = env_file.exists()
    residual_existed = residual_file.exists()
    original_env = env_file.read_bytes() if env_existed else None
    original_residual = residual_file.read_bytes() if residual_existed else None
    try:
        _atomic_write(env_file, env_content)
        _atomic_write(residual_file, residual_content)
    except OSError:
        if original_env is None:
            env_file.unlink(missing_ok=True)
        else:
            env_file.write_bytes(original_env)
        if original_residual is None:
            residual_file.unlink(missing_ok=True)
        else:
            residual_file.write_bytes(original_residual)
        raise


def migrate_config(
    source: Path,
    env_file: Path,
    residual_file: Path,
    *,
    dry_run: bool = False,
    force: bool = False,
) -> ConfigMigrationResult:
    """Split explicit legacy TOML values into deployment env and mutable overrides."""
    raw = _load_raw_config(
        source, allowed_fields=frozenset(RuntimeSettings.model_fields)
    )
    try:
        settings = RuntimeSettings.model_validate(
            RuntimeSettings().model_dump(mode="python") | raw
        )
    except ValidationError as exc:
        raise ConfigFileError(f"invalid configuration file {source}: {exc}") from exc
    values = settings.model_dump(mode="json")
    updates = {
        _environment_key(field_name): _environment_value(values[field_name])
        for field_name in sorted(DEPLOYMENT_RUNTIME_FIELDS & raw.keys())
        if values[field_name] is not None
    }
    residual = {
        field_name: values[field_name]
        for field_name in sorted(MUTABLE_RUNTIME_FIELDS & raw.keys())
    }
    original_env = env_file.read_text(encoding="utf-8") if env_file.exists() else ""
    merged_env = _merge_environment(original_env, updates, force=force)
    result = ConfigMigrationResult(
        deployment_keys=tuple(updates),
        residual_fields=tuple(residual),
        dry_run=dry_run,
    )
    if dry_run:
        return result
    _write_migration_targets(
        env_file,
        merged_env,
        residual_file,
        rtoml.dumps(residual),
    )
    return result
