"""Pure file operations for Lingchu runtime settings and their JSON Schema."""

from __future__ import annotations

import json
import os
from typing import TYPE_CHECKING, Any

from _lingchu_bot_contracts import (
    MutableRuntimeSettings,
)
from pydantic import ValidationError
import rtoml

if TYPE_CHECKING:
    from pathlib import Path

CONFIG_FILENAME = "runtime-overrides.toml"
CONFIG_SCHEMA_FILENAME = "runtime-overrides.schema.json"
LLM_CONFIG_FILENAME = "llm.toml"
_SCHEMA_DIRECTIVE = "#:schema ./runtime-overrides.schema.json\n"
_LLM_TEMPLATE = (
    "# Lingchu Bot uses Pydantic AI as the in-process LLM agent.\n"
    "# Edit [pydantic-ai] model to point to your provider/model.\n"
    "[pydantic-ai]\n"
    'model = "openai:gpt-5.2"\n'
    "timeout = 60.0\n"
    '# api_key_env = "LINGCHU_AI_API_KEY"\n'
    '# base_url = "https://api.openai.com/v1"\n'
    "\n"
    "[mcp]\n"
    "enabled = false\n"
    'review_profile = "default"\n'
    "max_tool_rounds = 5\n"
    "\n"
    "[observability]\n"
    "enabled = true\n"
)


class ConfigFileError(RuntimeError):
    """Report an expected configuration file failure to CLI callers."""


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(f"{path.suffix}.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def initialize_config(path: Path, *, force: bool = False) -> bool:
    """Create validated runtime defaults and return whether a file was written."""
    if path.exists() and not force:
        return False
    defaults = {
        key: value
        for key, value in MutableRuntimeSettings().model_dump(mode="json").items()
        if value is not None
    }
    _atomic_write(path, _SCHEMA_DIRECTIVE + rtoml.dumps(defaults))
    return True


def _seed_llm_pydantic_ai_from_env() -> str | None:
    """Build a loadable ``llm.toml`` from the ``LINGCHU_AI_MODEL`` env var.

    Seeds the ``[pydantic-ai]`` section when ``LINGCHU_AI_MODEL`` is present
    and non-empty. Other sections (``[mcp]``, ``[observability]``) use
    defaults that match :data:`_LLM_TEMPLATE`.

    Returns:
        The full TOML document text with the ``[pydantic-ai]``,
        ``[mcp]``, and ``[observability]`` sections, or ``None`` when
        seeding is not possible (``LINGCHU_AI_MODEL`` missing or empty).
    """
    model = os.environ.get("LINGCHU_AI_MODEL", "").strip()
    if not model:
        return None

    root: dict[str, Any] = {
        "pydantic-ai": {"model": model, "timeout": 60.0},
        "mcp": {
            "enabled": False,
            "review_profile": "default",
            "max_tool_rounds": 5,
        },
        "observability": {"enabled": True},
    }
    result = rtoml.dumps(root)
    return result if result.endswith("\n") else f"{result}\n"


def initialize_llm_config(path: Path) -> bool:
    """Create the default Pydantic AI LLM template without overwriting any file.

    When ``LINGCHU_AI_MODEL`` is set, the file is seeded with a loadable
    ``[pydantic-ai]`` section pointing to that model. Otherwise the commented
    example template is written so the user can edit it manually.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    content = _seed_llm_pydantic_ai_from_env() or _LLM_TEMPLATE
    try:
        with path.open("x", encoding="utf-8") as file:
            file.write(content)
    except FileExistsError:
        return False
    return True


def _load_raw_config(
    path: Path,
    *,
    allowed_fields: frozenset[str] = frozenset(MutableRuntimeSettings.model_fields),
) -> dict[str, object]:
    if not path.is_file():
        raise ConfigFileError(f"missing configuration file: {path}")
    try:
        raw = rtoml.load(path)
    except (OSError, rtoml.TomlParsingError) as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc
    unknown = sorted(set(raw) - allowed_fields)
    if unknown:
        raise ConfigFileError(f"unknown configuration fields: {', '.join(unknown)}")
    return raw


def validate_config(path: Path) -> MutableRuntimeSettings:
    """Validate one on-disk TOML file without environment overrides or writes."""
    raw = _load_raw_config(path)
    try:
        return MutableRuntimeSettings.model_validate(raw)
    except ValidationError as exc:
        raise ConfigFileError(f"invalid configuration file {path}: {exc}") from exc


def install_config_schema(config_dir: Path) -> Path:
    """Install the JSON Schema generated by the shared runtime settings model."""
    target = config_dir / CONFIG_SCHEMA_FILENAME
    content = json.dumps(
        MutableRuntimeSettings.model_json_schema(mode="serialization"),
        ensure_ascii=False,
        indent=2,
    )
    _atomic_write(target, f"{content}\n")
    return target
