name: 📚 文档部署
on:
  push:
    branches:
      - main
      - dev
    paths:
      - apps/docs/**
      - packages/**
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - turbo.json
      - .github/workflows/📚-docs.yml
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    name: 🚀 文档部署
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 配置 Pages
        uses: actions/configure-pages@v6.0.0

      - name: 检出代码
        uses: actions/checkout@v6.0.2

      - name: 配置 Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24

      - name: 配置 pnpm
        uses: pnpm/action-setup@v6.0.8

      - name: 安装 Node 依赖
        run: pnpm install --frozen-lockfile

      - name: 安装 Task
        uses: go-task/setup-task@v2.1.0

      - name: 构建文档
        run: task build:docs

      - name: 上传 Pages 产物
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: apps/docs/out

      - name: 部署到 Pages
        uses: actions/deploy-pages@v5.0.0
        id: deployment
